pip install appdirs
pip install APScheduler
pip install beautifulsoup4
pip install bs4
pip install certifi
pip install chardet
pip install Click
pip install colorize
pip install geojson
pip install google
pip install gTTS-token
pip install idna
pip install inflect
pip install jaraco.itertools
pip install joblib
pip install lxml
pip install mock
pip install more-itertools
pip install nltk
pip install numpy
pip install patch
pip install psutil
pip install PTable
pip install PyAudio
pip install pyowm
pip install pyttsx3
pip install pytz
pip install requests
pip install scikit-learn
pip install scipy
pip install six
pip install sklearn
pip install soupsieve
pip install SpeechRecognition
pip install speedtest-cli
pip install textblob
pip install tzlocal
pip install urllib3
pip install web-cache
pip install wikipedia
pip install wolframalpha
pip install xmltodict
