name: Auto Assign and Improve
permissions: write-all
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened, synchronize]

jobs:
  run: 
  runs_on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: 'Auto-assign issue'
      uses: pozil/auto-assign-issue@v1
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: rootgov
          numOfAssignee: 1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Test with pytest
      run: |
        pytest

    - name: Autopep8 Formatting
      uses: peter-evans/autopep8@v1
      with:
        args: --recursive --in-place --aggressive --aggressive .

    - name: 'Auto-fix issues'
      uses: some-autofix-action@v1 # replace this with an appropriate auto-fix action
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
