name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest, windows-latest, macos-latest, andriod-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
      
    - name: Cache
      uses: actions/cache@v3.2.5
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: 
        # An explicit key for restoring and saving the cache
        key: 
        # An ordered list of keys to use for restoring stale cache if no cache hit occurred for key. Note `cache-hit` returns false in this case.
        restore-keys: # optional
        # The chunk size used to split up large files during upload, in bytes
        upload-chunk-size: # optional
        # An optional boolean when enabled, allows windows runners to save or restore caches that can be restored or saved respectively on other platforms
        enableCrossOsArchive: # optional, default is false
        # Fail the workflow if cache entry is not found
        fail-on-cache-miss: # optional, default is false
